-- Flash Tech catalog + auth-adjacent tables
-- Run this in the Supabase SQL editor, then run seed.sql.

create table if not exists public.categories (
  slug text primary key,
  name text not null,
  blurb text,
  icon text,
  sort_order int not null default 0
);

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  description text not null default '',
  price numeric(12,2) not null check (price >= 0),
  category text not null,
  brand text,
  stock integer not null default 0 check (stock >= 0),
  images jsonb not null default '[]'::jsonb,
  specifications jsonb not null default '{}'::jsonb,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists products_category_idx on public.products (category);
create index if not exists products_active_idx on public.products (is_active);
create index if not exists products_name_idx on public.products (name);

create or replace function public.set_products_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists products_updated_at on public.products;
create trigger products_updated_at before update on public.products
for each row execute function public.set_products_updated_at();

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  first_name text,
  last_name text,
  username text,
  phone text,
  gender text,
  image text,
  address text,
  role text not null default 'user' check (role in ('user', 'admin')),
  updated_at timestamptz not null default now()
);

create table if not exists public.addresses (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  label text,
  full_name text,
  phone text,
  line1 text,
  city text,
  governorate text,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete set null,
  status text not null default 'Processing',
  total numeric not null,
  placed_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id bigint,
  title text not null,
  qty int not null,
  unit_price numeric not null,
  line_total numeric not null
);

create table if not exists public.contact_messages (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  email text not null,
  topic text,
  message text not null,
  created_at timestamptz not null default now()
);

create or replace function public.create_order_with_items(p_total numeric, p_items jsonb)
returns uuid
language plpgsql
security invoker
set search_path = public
as $$
declare
  created_order_id uuid;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  insert into public.orders (user_id, status, total)
  values (auth.uid(), 'Processing', p_total)
  returning id into created_order_id;

  insert into public.order_items (order_id, product_id, title, qty, unit_price, line_total)
  select created_order_id, item.product_id, item.title, item.qty, item.unit_price, item.line_total
  from jsonb_to_recordset(p_items) as item(
    product_id bigint,
    title text,
    qty int,
    unit_price numeric,
    line_total numeric
  );

  return created_order_id;
end;
$$;

insert into public.categories (slug, name, blurb, icon, sort_order) values
  ('laptops', 'Laptops', 'Work and gaming notebooks', 'laptop', 1),
  ('smartphones', 'Smartphones', 'Flagship and everyday phones', 'phone', 2),
  ('tablets', 'Tablets', 'Portable screens and iPad-class devices', 'tablet', 3),
  ('mobile-accessories', 'Accessories', 'Audio, cases, and charging', 'accessory', 4),
  ('mens-watches', 'Watches', 'Smart and classic timepieces', 'watch', 5),
  ('womens-watches', 'Watches', 'Smart and classic timepieces', 'watch', 6)
on conflict (slug) do nothing;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, first_name, last_name, username, image, role)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'first_name', split_part(coalesce(new.email, ''), '@', 1)),
    coalesce(new.raw_user_meta_data->>'last_name', ''),
    coalesce(new.raw_user_meta_data->>'username', split_part(coalesce(new.email, ''), '@', 1)),
    coalesce(new.raw_user_meta_data->>'avatar_url', new.raw_user_meta_data->>'picture', ''),
    'user'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.profiles enable row level security;
alter table public.addresses enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.contact_messages enable row level security;

create policy "public read categories" on public.categories for select using (true);
create policy "public read active products" on public.products
  for select using (is_active = true or public.is_admin());

create policy "read own profile" on public.profiles
  for select using (id = auth.uid());
create policy "admins read profiles" on public.profiles
  for select using (public.is_admin());
create policy "update own profile" on public.profiles
  for update using (id = auth.uid()) with check (id = auth.uid());

create policy "admins insert products" on public.products
  for insert with check (public.is_admin());
create policy "admins update products" on public.products
  for update using (public.is_admin()) with check (public.is_admin());
create policy "admins delete products" on public.products
  for delete using (public.is_admin());

create policy "admins insert categories" on public.categories
  for insert with check (public.is_admin());
create policy "admins update categories" on public.categories
  for update using (public.is_admin()) with check (public.is_admin());
create policy "admins delete categories" on public.categories
  for delete using (public.is_admin());

create policy "own addresses select" on public.addresses
  for select using (user_id = auth.uid());
create policy "own addresses insert" on public.addresses
  for insert with check (user_id = auth.uid());
create policy "own addresses delete" on public.addresses
  for delete using (user_id = auth.uid());

create policy "own orders select" on public.orders
  for select using (
    user_id = auth.uid()
    or exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
  );
create policy "own orders insert" on public.orders
  for insert with check (user_id = auth.uid());
create policy "admins update orders" on public.orders
  for update using (public.is_admin()) with check (public.is_admin());

create policy "own order items select" on public.order_items
  for select using (
    exists (select 1 from public.orders o where o.id = order_id and o.user_id = auth.uid())
    or exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
  );
create policy "own order items insert" on public.order_items
  for insert with check (
    exists (select 1 from public.orders o where o.id = order_id and o.user_id = auth.uid())
  );

create policy "anyone can contact" on public.contact_messages
  for insert with check (true);

create index if not exists products_brand_idx on public.products (brand);
create index if not exists orders_user_idx on public.orders (user_id);
create index if not exists addresses_user_idx on public.addresses (user_id);
