-- Flash Tech supporting store tables.
-- Run after the existing profiles table, public.is_admin(), and
-- products-migration.sql. This creates no sample products or orders.

create extension if not exists pgcrypto;

create table if not exists public.categories (
  slug text primary key check (slug = lower(slug) and slug !~ '[[:space:]]'),
  name text not null check (length(btrim(name)) > 0),
  blurb text,
  icon text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete set null,
  status text not null default 'Processing'
    check (status in ('Processing', 'In transit', 'Delivered', 'Cancelled')),
  total numeric(12,2) not null check (total >= 0),
  placed_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id uuid references public.products(id) on delete set null,
  title text not null,
  qty integer not null check (qty > 0),
  unit_price numeric(12,2) not null check (unit_price >= 0),
  line_total numeric(12,2) not null check (line_total >= 0)
);

create index if not exists orders_user_placed_idx on public.orders (user_id, placed_at desc);
create index if not exists order_items_order_idx on public.order_items (order_id);

create or replace function public.set_categories_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists categories_updated_at on public.categories;
create trigger categories_updated_at
before update on public.categories
for each row execute function public.set_categories_updated_at();

-- Grants allow PostgREST calls to reach RLS; RLS remains the authorization gate.
grant select on public.categories to anon, authenticated;
grant insert, update, delete on public.categories to authenticated;
grant select, insert, update on public.orders to authenticated;
grant select, insert on public.order_items to authenticated;
grant usage, select on sequence public.order_items_id_seq to authenticated;
grant select, update on public.profiles to authenticated;

alter table public.categories enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.profiles enable row level security;

drop policy if exists "public read categories" on public.categories;
create policy "public read categories" on public.categories
for select using (true);
drop policy if exists "admins insert categories" on public.categories;
create policy "admins insert categories" on public.categories
for insert to authenticated with check (public.is_admin());
drop policy if exists "admins update categories" on public.categories;
create policy "admins update categories" on public.categories
for update to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admins delete categories" on public.categories;
create policy "admins delete categories" on public.categories
for delete to authenticated using (public.is_admin());

drop policy if exists "read own profile" on public.profiles;
create policy "read own profile" on public.profiles
for select to authenticated using (id = auth.uid());
drop policy if exists "admins read profiles" on public.profiles;
create policy "admins read profiles" on public.profiles
for select to authenticated using (public.is_admin());
drop policy if exists "update own profile" on public.profiles;
create policy "update own profile" on public.profiles
for update to authenticated using (id = auth.uid()) with check (id = auth.uid());

drop policy if exists "own orders select" on public.orders;
create policy "own orders select" on public.orders
for select to authenticated using (user_id = auth.uid() or public.is_admin());
drop policy if exists "own orders insert" on public.orders;
create policy "own orders insert" on public.orders
for insert to authenticated with check (user_id = auth.uid());
drop policy if exists "admins update orders" on public.orders;
create policy "admins update orders" on public.orders
for update to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "own order items select" on public.order_items;
create policy "own order items select" on public.order_items
for select to authenticated using (
  exists (select 1 from public.orders where orders.id = order_id and (orders.user_id = auth.uid() or public.is_admin()))
);
drop policy if exists "own order items insert" on public.order_items;
create policy "own order items insert" on public.order_items
for insert to authenticated with check (
  exists (select 1 from public.orders where orders.id = order_id and orders.user_id = auth.uid())
);

create or replace function public.create_order_with_items(p_total numeric, p_items jsonb)
returns uuid
language plpgsql
security invoker
set search_path = public
as $$
declare
  created_order_id uuid;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  insert into public.orders (user_id, status, total)
  values (auth.uid(), 'Processing', p_total)
  returning id into created_order_id;

  insert into public.order_items (order_id, product_id, title, qty, unit_price, line_total)
  select created_order_id, item.product_id, item.title, item.qty, item.unit_price, item.line_total
  from jsonb_to_recordset(p_items) as item(
    product_id uuid,
    title text,
    qty integer,
    unit_price numeric,
    line_total numeric
  );

  return created_order_id;
end;
$$;

grant execute on function public.create_order_with_items(numeric, jsonb) to authenticated;
